slug: enterprise-tier
description: "A small tier is a cluster that has an instance, a worker and a db."

elements:
    - type: instance
      size: m1.large
      slug: web01

    - type: instance
      size: m1.large
      slug: web02

    - type: instance
      size: m1.large
      slug: web03

    - type: instance
      size: m1.large
      slug: worker01

    - type: instance
      size: m1.large
      slug: worker02

    - type: db
      size: m1.large
      slug: db01

    - type: db
      size: m1.large
      slug: db02
      connections:
          - type: slave
          - to: db01
    
    - type: instance
      size: m1.medium
      slug: jump01
