slug: enterprise-tier
description: "A small tier is a cluster that has an instance, a worker and a db."

elements:
    - type: instance
      size: m1.large
      slug: web01
      ami: ami-c7b202ae

    - type: instance
      size: m1.large
      slug: web02
      ami: ami-c7b202ae

    - type: instance
      size: m1.large
      slug: web03
      ami: ami-c7b202ae

    - type: instance
      size: m1.large
      slug: worker01
      ami: ami-c7b202ae

    - type: instance
      size: m1.large
      slug: worker02
      ami: ami-c7b202ae

    - type: db
      size: m1.large
      slug: db01
      storage: 10 

    - type: db
      size: m1.large
      slug: db02
      storage: 10 
      connections:
          - type: slave
          - to: db01
    
    - type: instance
      size: m1.medium
      slug: jump01
      ami: ami-c7b202ae
