slug: mid-tier
adapter: AWSAdapter
description: "A small tier is a cluster that has an instance, a worker and a db."

elements:
    - type: instance
      size: m1.large
      slug: web01
      ami: ami-c7b202ae

    - type: instance
      size: m1.large
      slug: web02
      ami: ami-c7b202ae

    - type: instance
      size: m1.medium
      slug: worker01
      ami: ami-c7b202ae

    - type: db
      size: m1.medium
      slug: db01
      storage: 10
    
    - type: instance
      size: m1.medium
      slug: bakery
      ami: ami-c7b202ae
