slug: mid-tier
adapter: AWSAdapter
description: "A small tier is a cluster that has an instance, a worker and a db."

elements:
    - type: instance
      size: m1.large
      slug: web01

    - type: instance
      size: m1.large
      slug: web02

    - type: instance
      size: m1.medium
      slug: worker01

    - type: db
      size: m1.medium
      slug: db01
    
    - type: instance
      size: m1.medium
      slug: bake
