slug: small-tier
adapter: AWSAdapter
description: "A small tier is a cluster that has an instance, a worker and a db."

elements:
    - type: instance
      size: m1.medium
      name: web01

    - type: instance
      size: m1.medium
      name: worker01

    - type: db
      size: m1.medium
      name: db01
    
    - type: instance
      size: m1.medium
      name: bake
