slug: small-tier
adapter: AWSAdapter
description: "A small tier is a cluster that has an instance, a worker and a db."

elements:
    - type: instance
      size: m1.medium
      slug: web01
      ami: ami-c7b202ae

    - type: instance
      size: m1.medium
      slug: worker01
      ami: ami-c7b202ae

    - type: db
      size: m1.medium
      slug: db01
    
    - type: instance
      size: m1.medium
      slug: bake
      ami: ami-c7b202ae
