name: Web Cube Cloud
description: The Web Cube Cloud Supercluster

clusters: 
    - slug: rerun
      type: small-tier
   
    - slug: uemaxim
      type: small-tier

    - slug: manduka
      type: mid-tier

    - slug: ibm
      type: enterprise-tier
